# -*- coding: utf-8 -*-
"""Spotify_dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iGGkroCITNyUspDwEVT6ZUjWJaTva3gw
"""

# !pip install streamlit pandas matplotlib seaborn

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv("colaab/Spotify+Streaming+History/spotify_cleaned.csv")
df.head()

#Sidebar filter
st.sidebar.header("Filter")
selected_artist = st.sidebar.multiselect("Pilih Artis", df["artist_name"].unique())
selected_platform = st.sidebar.multiselect("Pilih Platform", df["platform"].unique())

#Filter data berdasarkan pilihan
if selected_artist:
  df = df[df["artist_name"].isin(selected_artist)]
if selected_platform:
  df = df[df["platform"].isin(selected_platform)]

# DASHBOARD UTAMA
st.title("Spotify Streaming Dashboard")
st.markdown("Dashboard interaktif untuk menganalisis Spotify Streaming History")

#Total Streaming Time
total_hours = df["ms_played"].sum() / (1000*60*60) #convert ms ke jam
st.metric("Total Waktu Mendengarkan Musik (Jam)", f"{total_hours:.2f} jam")

# Top 10 artis
st.subheader("Top 10 Artis berdasarkan Waktu Mendengarkan")
top_artists = df["artist_name"].value_counts().head(10)
fig, ax = plt.subplots()
top_artists.plot(kind="bar", color="skyblue", ax=ax)
ax.set_xlabel("Artis")
ax.set_ylabel("Jumlah Waktu (Jam)")
st.pyplot(fig)

# Platform yang sering digunakan
st.subheader("Platform yang paling sering digunakan")
platform_counts = df["platform"].value_counts()
fig, ax = plt.subplots()
platform_counts.plot(kind="bar", color="orange", ax=ax)
st.pyplot(fig)

#Alasan Memulai Lagu
st.subheader("Alasan Memulai Lagu")
reason_start_counts = df["reason_start"].value_counts()
st.bar_chart(reason_start_counts)

#Alasan Mengakhiri Lagu
st.subheader("Alasan Mengakhiri Lagu")
reason_end_counts = df["reason_end"].value_counts()
st.bar_chart(reason_end_counts)

#heatmap waktu favorit mendengarkan lagu
st.subheader("Hatmap Waktu Favorit Mendengarkan Musik")
heatmap_data = df.pivot_table(index="day", columns="hour", values="ms_played", aggfunc="count")
fig, ax = plt.subplots(figsize=(10,5))
sns.heatmap(heatmap_data, cmap="Blues", ax=ax)
st.pyplot(fig)

#Skip & Shuffle Rate
st.subheader("Persentase Skip & Shuffle")
col1, col2 = st.columns(2)
col1.metric("Jumlah Skip", df["skipped"].sum())
col2.metric("Jumlah Shuffle", df["shuffle"].sum())

